### ISSUE TITLE
Add more events external code can subscribe to

### ISSUE THREAD

**Issue by corp-0** [Cardioxo/unitystation#7]
- [x] ApplyDamageEvent
- [x] ConciousStateEvent
- [x] FireStackEvent
- [x] OnDeathNotifyEvent
- [ ] OnSoftCritEvent
- [ ] OnCritEvent
- [ ] OnClonedEvent (allow for clone damage to happen?)

USE REGIONS and declare all events together

**Comment by corp-0** [comment]
@Cardioxo what other events you want to make? Add them to the checked list in this issue

**Comment by Cardioxo** [comment]
It's probably better to add more events should there be anything that will need it in the near future. I can't think of anything where the SoftCritEvent/CritEvent will be needed. I will close this
